show databases;

-- 데이터베이스 생성
create database kiki;
use kiki;

-- 언어테이블
CREATE TABLE LANGUAGE (
	LANG_CODE INT(2) NOT NULL,
	LANG_NAME VARCHAR(20) NOT NULL
);

-- 버전 테이블
CREATE TABLE VERSION (
	VERSION_CODE INT(3) NOT NULL,
	VERSION_NAME VARCHAR(10) NOT NULL
);

-- 업데이트(APP) 테이블
CREATE TABLE UPDATE_APP (
	VERSION_CODE INT(3) NOT NULL,
	UPDATE_CONTENT VARCHAR(300) 
);

-- 버킷 분류 테이블
CREATE TABLE CATEGORY_BUCKET (
	CATEGORY_CODE INT(2) NOT NULL,
	CATEGORY_NAME VARCHAR(20) NOT NULL 
);

-- 사용자 생성 테이블
CREATE TABLE USER_MOBILE (
	OS VARCHAR(10) ,
	PHONE VARCHAR(20) ,
	NICKNAME VARCHAR(30) ,
	VERSION_NAME VARCHAR(10),
	MARKET VARCHAR(20) ,
	LANG VARCHAR(20) ,
	COUNTRY VARCHAR(20),
	LAST_DT VARCHAR(20),
	CREATE_DT  VARCHAR(20),
	GCM_TOKEN VARCHAR(300)
);

-- 마켓 테이블
CREATE TABLE MARKET_INFO (
	MARKET_CODE INT(2) NOT NULL ,
	MARKET VARCHAR(10) NOT NULL
);

-- 버킷  테이블
CREATE TABLE BUCKET (
	CATEGORY_CODE INT(2) NOT NULL,
	CONTENT VARCHAR(300) NOT NULL,
	IMAGE_URL VARCHAR(100) ,
	NICKNAME VARCHAR(30) ,
	PHONE VARCHAR(20) ,
	CREATE_DT  VARCHAR(20) NOT NULL,
	IDX INT(10) unsigned NOT NULL AUTO_INCREMENT,
	PRIMARY KEY (IDX)
);


-- 댓글  테이블
CREATE TABLE COMMENT (
	NICKNAME VARCHAR(30) ,
	CONTENT VARCHAR(300) NOT NULL,
	CREATE_DT  VARCHAR(20) NOT NULL,
	BUCKET_NO INT(10) NOT NULL,
	IDX INT(10) unsigned NOT NULL AUTO_INCREMENT,
	PRIMARY KEY (IDX)
);

-- 사용자  테이블
CREATE TABLE ACCOUNT (
	USERNAME VARCHAR(100) ,
	ID VARCHAR(100) NOT NULL,
	PASSWORD  VARCHAR(100) NOT NULL,
	IDX INT(10) unsigned NOT NULL AUTO_INCREMENT,
	PRIMARY KEY (IDX)
);


-- 테이블에 칼럼 추가하기
ALTER TABLE VERSION ADD UPDATE_FORCE varchar(1) NULL;

-- 지금까지 강제/선택 여부 없으므로 수정
UPDATE VERSION SET UPDATE_FORCE = 'N';


-- 방문자 카운트 조회용 테이블 추가
CREATE TABLE TODAY_CNT(
	DATE  VARCHAR(100) NOT NULL,
	IDX INT(10) unsigned NOT NULL 
);

-- 테이블에 칼럼 수정하기
ALTER TABLE TODAY_CNT MODIFY DATE VARCHAR(12) NOT NULL;


-- 서버IP 관리 테이블
CREATE TABLE IP (
	VERSION_CODE INT(3) NOT NULL,
	VERSION_NAME VARCHAR(10) NOT NULL
);

-- 테이블에 칼럼 수정하기
ALTER TABLE IP MODIFY VERSION_NAME VARCHAR(15) NOT NULL;

-- 테이블에 칼럼 수정하기
ALTER TABLE USER_MOBILE ADD OS_VERSION VARCHAR(10) NULL;
ALTER TABLE USER_MOBILE ADD TEL_GBN VARCHAR(10) NULL;

-- 테이블에 칼럼 삭제하기
ALTER TABLE USER_MOBILE DROP CREATE_DT;

--버킷 테이블에 칼럼 추가하기
ALTER TABLE BUCKET ADD HIDDEN VARCHAR(1) NULL;

--사용자 테이블에 칼럼 추가하기
ALTER TABLE USER_MOBILE ADD VISITS VARCHAR(1) NULL;
--사용자 방문수 최초이므로 모두 0으로 업데이트
UPDATE USER_MOBILE SET VISITS = '0';
-- 테이블에 칼럼 수정하기
ALTER TABLE USER_MOBILE MODIFY VISITS VARCHAR(10) NOT NULL;

-- 테이블에 칼럼 수정하기
ALTER TABLE USER_MOBILE MODIFY TEL_GBN VARCHAR(30) NULL;

-- 버킷 랭킹  테이블
CREATE TABLE BUCKET_RANK (
	CATEGORY_CODE INT(2) NOT NULL,
	CONTENT VARCHAR(300) NOT NULL,
	BEST_CNT INT(2) NULL,
	GOOD_CNT INT(2) NULL,
	SOSO_CNT INT(2) NULL,
	IDX INT(10) unsigned NOT NULL AUTO_INCREMENT,
	PRIMARY KEY (IDX)
);

-- 버킷 랭킹 사용자별  테이블
CREATE TABLE BUCKET_RANK_USER (
	CATEGORY_CODE INT(2) NULL,
	CONTENT VARCHAR(300) NOT NULL,
	COMMENT INT(2) NULL,
	PHONE VARCHAR(20) ,
	NICKNAME VARCHAR(30) ,
	BUCKET_RANK_IDX INT(10) unsigned NOT NULL,
	HISTORY_IDX INT(10) unsigned NOT NULL AUTO_INCREMENT,
	PRIMARY KEY (HISTORY_IDX)
);

-- 테이블에 칼럼 수정하기
ALTER TABLE BUCKET_RANK MODIFY CATEGORY_CODE INT(2) NULL;

-- 테이블에 칼럼 수정하기
ALTER TABLE BUCKET_RANK_USER MODIFY CONTENT VARCHAR(300) NULL;

-- 사용자  DB  테이블
CREATE TABLE DB_HISTORY (
	NICKNAME VARCHAR(30) NOT NULL,
	DB_NAME VARCHAR(100) ,
	CREATE_DT  VARCHAR(20) NOT NULL,
	IDX INT(10) unsigned NOT NULL AUTO_INCREMENT,
	PRIMARY KEY (IDX)
);

-- 채팅  DB  테이블(방 입장 및 퇴장 관리)
CREATE TABLE CHAT_HISTORY (
	CHAT_IDX  VARCHAR(20) NOT NULL,
	PHONE VARCHAR(20) NOT NULL,
	NICKNAME VARCHAR(30) ,
	CONTENT VARCHAR(300) NOT NULL,
	CREATE_DT  VARCHAR(20) ,
	IDX INT(10) unsigned NOT NULL AUTO_INCREMENT,
	PRIMARY KEY (IDX)
);

--채팅 테이블에 칼럼 추가하기
ALTER TABLE CHAT_HISTORY ADD HIDDEN VARCHAR(1) NULL;
ALTER TABLE CHAT_HISTORY ADD STATUS VARCHAR(1) NULL;

-- 테이블에 칼럼 삭제하기
ALTER TABLE CHAT_HISTORY DROP CONTENT;

-- 채팅 내용 DB
CREATE TABLE CHAT (
	CHAT_IDX  VARCHAR(20) NOT NULL,
	PHONE VARCHAR(20) NOT NULL,
	NICKNAME VARCHAR(30) ,
	CONTENT VARCHAR(300) NOT NULL,
	CREATE_DT  VARCHAR(20) ,
	IDX INT(10) unsigned NOT NULL AUTO_INCREMENT,
	PRIMARY KEY (IDX)
);

ALTER TABLE CHAT ADD SEQ INT(10) unsigned ;

-- 카데고리 AI
CREATE TABLE CATEGORY_AI (
	CATEGORY_CODE  VARCHAR(100) NOT NULL,
	CATEGORY_NAME VARCHAR(100) NOT NULL,
	PRIMARY KEY (CATEGORY_CODE)
);

--  AI 스크리트
CREATE TABLE AI_SCRIPT (
	CATEGORY_CODE  VARCHAR(100) NOT NULL,
	CONTENT VARCHAR(300) NOT NULL,
	IDX INT(10) unsigned NOT NULL AUTO_INCREMENT,
	PRIMARY KEY (IDX)
);


