
-- 언어테이블
INSERT LANGUAGE (LANG_CODE, LANG_NAME) Values(1, 'KO');
INSERT LANGUAGE (LANG_CODE, LANG_NAME) Values(2, 'ENG');


-- 버전 테이블
INSERT VERSION (VERSION_CODE, VERSION_NAME) Values(1, '1.0.0');
INSERT VERSION (VERSION_CODE, VERSION_NAME) Values(2, '1.0.1');
INSERT VERSION (VERSION_CODE, VERSION_NAME) Values(3, '1.0.2');
INSERT VERSION (VERSION_CODE, VERSION_NAME) Values(4, '1.0.3');


-- 업데이트(APP) 테이블
INSERT UPDATE_APP (VERSION_CODE, UPDATE_CONTENT) Values(1, 'App 1.0.0
1.드림 리스트 메모 기능
2. 비밀번호 기능');

INSERT UPDATE_APP (VERSION_CODE, UPDATE_CONTENT) Values(2, 'App 1.0.1
1. 완료된 목록에서도 상세화면 보기/수정 가능
2. 일부 화면 세로모드로 화면 수정
3. 백키 기능 정의
4. 버전 확인 기능 추가');

INSERT UPDATE_APP (VERSION_CODE, UPDATE_CONTENT) Values(3, 'App 1.0.2 
1. 위젯 기능 추가
2. 드림 리스트 카메라로 이미지 추가
3. 완료된 목록에서 이미지 보기
4. 환경설정 기능 DB 백업 기능 추가
5. 완료된 목록 화면 수정');

INSERT UPDATE_APP (VERSION_CODE, UPDATE_CONTENT) Values(4, 'App 1.0.3
1. 인트로 애니메이션 추가
2. 팝업 추가
3. 버킷 입력 후 포커스 이동
4. DB복원 기능 추가');


-- 버킷 분류 테이블
INSERT CATEGORY_BUCKET (CATEGORY_CODE, CATEGORY_NAME) Values(1, 'LIFE');
INSERT CATEGORY_BUCKET (CATEGORY_CODE, CATEGORY_NAME) Values(2, 'LOVE');
INSERT CATEGORY_BUCKET (CATEGORY_CODE, CATEGORY_NAME) Values(3, 'WORK');
INSERT CATEGORY_BUCKET (CATEGORY_CODE, CATEGORY_NAME) Values(4, 'EDUCATION');
INSERT CATEGORY_BUCKET (CATEGORY_CODE, CATEGORY_NAME) Values(5, 'FAMILY');
INSERT CATEGORY_BUCKET (CATEGORY_CODE, CATEGORY_NAME) Values(6, 'FINANCE');
INSERT CATEGORY_BUCKET (CATEGORY_CODE, CATEGORY_NAME) Values(7, 'DEVELOP');
INSERT CATEGORY_BUCKET (CATEGORY_CODE, CATEGORY_NAME) Values(8, 'HEALTH');
INSERT CATEGORY_BUCKET (CATEGORY_CODE, CATEGORY_NAME) Values(9, 'ETC');


-- 사용자 생성 테이블
INSERT USER_MOBILE (OS, PHONE, VERSION_NAME) Values('A', '01050666713', '1.0.3');

-- 마켓 테이블
INSERT MARKET_INFO (MARKET_CODE, MARKET) Values(1, 'GOOGLE');
INSERT MARKET_INFO (MARKET_CODE, MARKET) Values(2, 'APPLE');
INSERT MARKET_INFO (MARKET_CODE, MARKET) Values(3, 'TSTORE');
INSERT MARKET_INFO (MARKET_CODE, MARKET) Values(3, 'NAVER');

-- 버킷  테이블
INSERT BUCKET (CATEGORY_CODE, CONTENT, CREATE_DT) Values(1, '퇴사하기', '2015-12-18 15:32:41');

-- 댓글  테이블
INSERT COMMENT (CONTENT, CREATE_DT, BUCKET_NO) Values('수고헀습니다', '20151208200001', 1);

-- 사용자  테이블
INSERT ACCOUNT (USERNAME, ID, PASSWORD) Values('admin', 'admin','fpdlel0102.');

-- 서버 IP 관리 테이블
INSERT IP (VERSION_CODE, VERSION_NAME) Values(1, '222.112.228.184');

-- 버킷 테이블 모두 보이게 처리
UPDATE BUCKET SET HIDDEN = 'N';

-- 버킷 랭킹 테이블
INSERT BUCKET_RANK (CONTENT) Values('번지 점프 하기');
INSERT BUCKET_RANK (CONTENT) Values('패러글라이딩 하기');
INSERT BUCKET_RANK (CONTENT) Values('행복한 결혼 하기');
INSERT BUCKET_RANK (CONTENT) Values('악기 1개 배우기');
INSERT BUCKET_RANK (CONTENT) Values('재능 기부하기');
INSERT BUCKET_RANK (CONTENT) Values('한자 자격증 따기');
INSERT BUCKET_RANK (CONTENT) Values('내집 마련하기');
INSERT BUCKET_RANK (CONTENT) Values('제주도 여행가기');
INSERT BUCKET_RANK (CONTENT) Values('전국 여행하기');
INSERT BUCKET_RANK (CONTENT) Values('제2외국어 배워보기');

INSERT BUCKET_RANK (CONTENT) Values('마라톤 도전해보기');
INSERT BUCKET_RANK (CONTENT) Values('유럽 배낭여행 해보기');
INSERT BUCKET_RANK (CONTENT) Values('좋아하는 공연 보러가기');
INSERT BUCKET_RANK (CONTENT) Values('애완동물 함께하기 ');
INSERT BUCKET_RANK (CONTENT) Values('인생샷 남기기');
INSERT BUCKET_RANK (CONTENT) Values('정원 만들기');
INSERT BUCKET_RANK (CONTENT) Values('미술 배워보기');
INSERT BUCKET_RANK (CONTENT) Values('수영 배우기');
INSERT BUCKET_RANK (CONTENT) Values('첫사랑 만나기');
INSERT BUCKET_RANK (CONTENT) Values('가족 사진 찍기');



