-- 테이블에 칼럼 추가하기
ALTER TABLE VERSION ADD UPDATE_FORCE varchar(1) NULL;

-- 지금까지 강제/선택 여부 없으므로 수정
UPDATE VERSION SET UPDATE_FORCE = 'N';

-- 테이블에 칼럼 수정하기
ALTER TABLE TODAY_CNT MODIFY DATE VARCHAR(12) NOT NULL;

-- 테이블에 칼럼 수정하기
ALTER TABLE IP MODIFY VERSION_NAME VARCHAR(15) NOT NULL;

-- 테이블에 칼럼 수정하기
ALTER TABLE USER_MOBILE ADD OS_VERSION VARCHAR(10) NULL;
ALTER TABLE USER_MOBILE ADD TEL_GBN VARCHAR(10) NULL;

-- 테이블에 칼럼 삭제하기
ALTER TABLE USER_MOBILE DROP CREATE_DT;

--버킷 테이블에 칼럼 추가하기
ALTER TABLE BUCKET ADD HIDDEN VARCHAR(1) NULL;

--사용자 테이블에 칼럼 추가하기
ALTER TABLE USER_MOBILE ADD VISITS VARCHAR(1) NULL;

--사용자 방문수 최초이므로 모두 0으로 업데이트
UPDATE USER_MOBILE SET VISITS = '0';

-- 테이블에 칼럼 수정하기
ALTER TABLE USER_MOBILE MODIFY VISITS VARCHAR(10) NOT NULL;

-- 테이블에 칼럼 수정하기
ALTER TABLE USER_MOBILE MODIFY TEL_GBN VARCHAR(30) NULL;

-- 테이블에 칼럼 수정하기
ALTER TABLE BUCKET_RANK MODIFY CATEGORY_CODE INT(2) NULL;

-- 테이블에 칼럼 수정하기
ALTER TABLE BUCKET_RANK_USER MODIFY CONTENT VARCHAR(300) NULL;

-- 버킷 랭킹 칼럼 디폴트로 설정하기
ALTER TABLE BUCKET_RANK ALTER BEST_CNT SET DEFAULT 0;
ALTER TABLE BUCKET_RANK ALTER GOOD_CNT SET DEFAULT 0;
ALTER TABLE BUCKET_RANK ALTER SOSO_CNT SET DEFAULT 0;

-- 버킷 랭킹 사용자 히스토리 칼럼 디폴트로 설정하기
ALTER TABLE BUCKET_RANK_USER ALTER COMMENT SET DEFAULT 0;

-- 공지내용 versionCode 자동 증가값 설정하기
ALTER TABLE UPDATE_APP MODIFY VERSION_CODE INT(3) unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY ;

--charset
set character set utf8;

-- 칼럼 추가하기
ALTER TABLE TODAY_CNT ADD APP_GBN VARCHAR(50) NULL;
UPDATE TODAY_CNT SET APP_GBN = 'momo.kikiplus.com.kbucket';


-- 채팅 칼럼 디폴트로 설정하기
ALTER TABLE CHAT ALTER SEQ SET DEFAULT 0;

-- 이모지 사용
ALTER DATABASE kiki CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci;
ALTER TABLE comment CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

--DB 히스토리 테이블에 칼럼 추가하기
ALTER TABLE DB_HISTORY ADD NICKNAME VARCHAR(30) NULL;
ALTER TABLE DB_HISTORY MODIFY PHONE VARCHAR(20) NULL;

-- 테이블에 칼럼 삭제하기
ALTER TABLE CHAT DROP PHONE;
-- 테이블에 칼럼 수정하기
ALTER TABLE CHAT MODIFY PHONE VARCHAR(20) NULL;

--수정
UPDATE BUCKET SET HIDDEN = 'N';

-- 테이블에 칼럼 삭제하기
ALTER TABLE USER_MOBILE ADD PHONE VARCHAR(20) NULL;
UPDATE USER_MOBILE SET PHONE = "";
